### PR TITLE
update includepath for wasm project

### PR DESCRIPTION
**Pull request by laxa88**
Adds includePath for VS when switching to WASM build, so you don't get red squiggly lines in the IDE

### CODE REVIEW

**Comment by schellingb** [comment]
Hi
Instead of adding it to the generated game vcxproj files, this should be added to the global ZillaApp-vs.props file.

If you were to change the already existing sections in ZillaApp-vs.props to this, does it work the same as the PR does for you?
```xml
  <PropertyGroup Condition="'$(Configuration)'=='WebAssembly-Debug'">
    <OutDir>Debug-wasm\</OutDir>
    <NMakeBuildCommandLine>"$(ZillaLibDir)/Tools/make.exe" --no-print-directory -f "$(ZillaLibDir)/WebAssembly/ZillaLibWasm.mk" "ZillaApp=$(ProjectName)" MSVC=1</NMakeBuildCommandLine>
    <NMakeReBuildCommandLine>"$(ZillaLibDir)/Tools/make.exe" -B --no-print-directory -f "$(ZillaLibDir)/WebAssembly/ZillaLibWasm.mk" "ZillaApp=$(ProjectName)" MSVC=1</NMakeReBuildCommandLine>
    <NMakeCleanCommandLine>"$(ZillaLibDir)/Tools/make.exe" --no-print-directory -f "$(ZillaLibDir)/WebAssembly/ZillaLibWasm.mk" "ZillaApp=$(ProjectName)" clean</NMakeCleanCommandLine>
    <LocalDebuggerCommand>$(ZillaLibDir)/Tools/make.exe</LocalDebuggerCommand>
    <LocalDebuggerCommandArguments>--no-print-directory -f "$(ZillaLibDir)/WebAssembly/ZillaLibWasm.mk" "ZillaApp=$(ProjectName)" run RUNWITHOUTBUILD=1</LocalDebuggerCommandArguments>
    <NMakePreprocessorDefinitions>__wasm__</NMakePreprocessorDefinitions>
    <IncludePath>$(ZillaLibDir)/Include</IncludePath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='WebAssembly-Release'">
    <OutDir>Release-wasm\</OutDir>
    <NMakeBuildCommandLine>"$(ZillaLibDir)/Tools/make.exe" --no-print-directory -f "$(ZillaLibDir)/WebAssembly/ZillaLibWasm.mk" "ZillaApp=$(ProjectName)" BUILD=RELEASE MSVC=1</NMakeBuildCommandLine>
    <NMakeReBuildCommandLine>"$(ZillaLibDir)/Tools/make.exe" -B --no-print-directory -f "$(ZillaLibDir)/WebAssembly/ZillaLibWasm.mk" "ZillaApp=$(ProjectName)" BUILD=RELEASE MSVC=1</NMakeReBuildCommandLine>
    <NMakeCleanCommandLine>"$(ZillaLibDir)/Tools/make.exe" --no-print-directory -f "$(ZillaLibDir)/WebAssembly/ZillaLibWasm.mk" "ZillaApp=$(ProjectName)" BUILD=RELEASE clean</NMakeCleanCommandLine>
    <LocalDebuggerCommand>$(ZillaLibDir)/Tools/make.exe</LocalDebuggerCommand>
    <LocalDebuggerCommandArguments>--no-print-directory -f "$(ZillaLibDir)/WebAssembly/ZillaLibWasm.mk" "ZillaApp=$(ProjectName)" BUILD=RELEASE run RUNWITHOUTBUILD=1</LocalDebuggerCommandArguments>
    <NMakePreprocessorDefinitions>__wasm__</NMakePreprocessorDefinitions>
    <IncludePath>$(ZillaLibDir)/Include</IncludePath>
  </PropertyGroup>
```

Thanks!

**Comment by schellingb** [comment]
Hmm, this probably should be added to all the targets that use NMake style command execution.
WebAssembly-Debug, WebAssembly-Release, Emscripten-Debug, Emscripten-Release, NACL-Debug, NACL-Release, Android-Debug, Android-Release

**Comment by laxa88** [comment]
@schellingb Thanks for the suggestion! Yes it works, thank you. I only updated for Android and WASM because those are the only options I see in VS IDE anyway:

snip

Not sure if adding for emscripten, NACL would affect anywhere?

**Comment by schellingb** [comment]
Hooray, thanks for confirming

**Pull request merged**
